eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: grd
    prefer-ip-address: true

server:
  port: 7000

spring:
  application:
    name: grd
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true